<?php
use \Phalcon\Mvc\Router;


class IndexController extends ControllerBase
{

    public function initialize()
    {
        return parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $this->view->disable();
        echo $this->view->getRender('layouts', 'index');
    }

    public function notFoundAction()
    {
        $this->view->disable();
        echo $this->view->getRender('layouts', '404');
    }

}

